site_name: Apuntes sobre Java
#site_url: https://ea57-ua.github.io/java
#repo_url: https://github.com/ea57-ua/java
use_directory_urls: false

nav:
- 'Indice': 'index.md'
- 'Excepciones': 'java/excepciones.md'
- 'Herencia': 'java/herencia.md'

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


# Ponemos como idioma de búsqueda el inglés
# para conseguir que busque correctamente
# todas las palabras en castellano, sin eliminar
# los excesivos derivados que se definen en
# https://github.com/MihaiValentin/lunr-languages/blob/master/lunr.es.js

extra:
    search:
        language: 'en'

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
    - footnotes
    - meta
    - sane_lists
    - toc:
       permalink: true
       toc_depth: 3
    - pymdownx.superfences
